# Generated by Django 3.0.9 on 2020-08-10 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Seslan', max_length=30)),
                ('date', models.DateTimeField(verbose_name='Date of Game')),
                ('description', models.TextField(max_length=1000, verbose_name='Game description')),
                ('game_time', models.FloatField(default=0, verbose_name='In game time')),
            ],
        ),
        migrations.CreateModel(
            name='Game_event_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30, verbose_name='Name of object image')),
                ('file_field', models.ImageField(upload_to='Models')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='Log file Name')),
                ('file_path', models.CharField(default='Logs/', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Maps/')),
            ],
        ),
        migrations.CreateModel(
            name='Proffesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proffesion_name', models.CharField(max_length=30, verbose_name='Proffesion')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Game')),
                ('proffesion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='game.Proffesion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Some object', max_length=20)),
                ('time', models.FloatField(default=0)),
                ('is_news', models.BooleanField(default=True)),
                ('release', models.BooleanField(default=False)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Game_event_image')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='log_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='game.Log'),
        ),
        migrations.AddField(
            model_name='game',
            name='map',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='game.Map'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game_event')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Information')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
            ],
        ),
    ]
