# Generated by Django 3.0.9 on 2020-08-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='map',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='game.Map'),
        ),
    ]
