# Generated by Django 3.0.9 on 2020-08-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(default='map', max_length=100),
            preserve_default=False,
        ),
    ]
