# Generated by Django 3.0.9 on 2020-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_map_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_event',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
