# Generated by Django 3.0.9 on 2020-08-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(default='Theare are description of object', max_length=1000)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game_event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
            ],
        ),
    ]
