# Generated by Django 3.0.9 on 2020-08-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='visible_objects',
        ),
    ]
