# Generated by Django 3.0.9 on 2020-08-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200808_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='user_id',
            new_name='player_id',
        ),
    ]
