# Generated by Django 3.0.9 on 2020-08-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200808_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_event',
            name='information',
        ),
    ]
