# Generated by Django 3.0.9 on 2020-08-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_game_event_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_event_image',
            name='file_field',
            field=models.ImageField(upload_to='Models'),
        ),
    ]
