# Generated by Django 3.0.9 on 2020-08-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200808_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='game_event',
            old_name='pox_y',
            new_name='pos_y',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='user',
        ),
    ]
