# Generated by Django 3.0.9 on 2020-08-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20200808_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_event',
            name='is_news',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game_event',
            name='release',
            field=models.BooleanField(default=False),
        ),
    ]
