# Generated by Django 3.0.9 on 2020-08-10 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0013_auto_20200810_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='proffesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Proffesion'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
